### ISSUE TITLE
Warning! Unmet python dependencies!

### ISSUE THREAD

**Issue by lukebranch** [adhoc-dev/odoo-addons#1]
@jjscarafia 

I'm having some issues installing the product_catalog_aeroo_report module due to some issues with installing the dependencies required for aeroo on Ubuntu 14.04 with Odoo 8.0. The error message i've seen is as follows:

Warning! Unmet python dependencies!

No module named unohelper
No module named com.sun.star.beans
No module named com.sun.star.uno
No module named com.sun.star.connection
No module named com.sun.star.beans
No module named com.sun.star.lang
No module named com.sun.star.io
No module named com.sun.star.io

It looks as if python-uno has been dropped from Ubuntu 14.04 repositories, although Aeroo seems to depend on it. Are you aware of any way to resolve this issue for 14.04, or would you recommend downgrading to an earlier version of Ubuntu for this reason? I'm very interested in trying the product_catalog_aeroo_report module for exporting and printing product catalogs, but I have hit a roadblock when it comes to this issue and I have searched for weeks to try and find a solution.

There are a huge number of forum posts mentioning the issue, however I have sifted through all that I can find and attempted a large number of the suggestions and as of yet I have had no luck.

Any help or advice would be much appreciated. I am happy to pay for your help resolving the issue, however I would like to know what is required so that I can replicate it in other instances I setup.

**Comment by diassynthesis** [comment]
Try to install LibreOffice: sudo aptitude install -y libreoffice libreoffice-script-provider-python

**Comment by lukebranch** [comment]
@diassynthesis , thanks for the suggestion. Unfortunately uno seems to have been removed from the libreoffice packages in Ubuntu 14.04. Unfortunately i'm still stuck on this issue and can't get the aeroo_report_ooo plugin to work in 8.0 either due to this same issue.

**Comment by lisandrogallo** [comment]
Did you try to install 'uno' package directly from PIP? If that fails then this gist can be helpful:

https://gist.github.com/hbrunn/6f4a007a6ff7f75c0f8b

**Comment by jjscarafia** [comment]
Muy bueno liso! Ahora en la v8, aeroo usa un modulo distinto que usa python
3 con el libreoffice que viene por defecto por lo menos en ubuntu 14.04.
Abrazo!

_Ing. Juan José Scarafía_
(+54 9 341)153 278039
skype: jjscarafia
twitter: @jjscarafia https://twitter.com/jjscarafia
github: @jjscarafia https://github.com/jjscarafia
www.ingadhoc.com

2015-01-05 9:53 GMT-03:00 Liso Gallo notifications@github.com:

**Comment by jjscarafia** [comment]
We are no longer using report_aeroo_ooo in v8, I close the issue that is more related to aeroo installation
