### ISSUE TITLE
sale_stock_availability show only zero

### ISSUE THREAD

**Issue by Netzvamp** [adhoc-dev/odoo-addons#109]
Hello,
looks like the sale_stock_availability addon doesn't work. It shows only zero, despite there are items in stock. 
![image](https://cloud.githubusercontent.com/assets/4619406/9274052/73d3d78e-4292-11e5-9aa6-0ad89e9500ad.png)

**Comment by jjscarafia** [comment]
It's working for us and owr customers. 
It show stock of the product in the sale order warehouse.
![image](https://cloud.githubusercontent.com/assets/3016656/9275841/633a4546-4276-11e5-8416-04032dcd00b4.png)
