### ISSUE TITLE
inter_company_rules not creating SO from PO

### ISSUE THREAD

**Issue by mustafaengg** [adhoc-dev/odoo-addons#110]
Sale order not being created within multi company, Company A defined as supplier for company B.
When creating a purchase order for company A from company B no Sale order is being created in Company A?

**Comment by jjscarafia** [comment]
It depens on your configuration on each company on the company (tab configuration, group Inter-Company Rules). 
Please follow this guide to report an issue
https://github.com/ingadhoc/odoo-argentina/wiki/Reporting-Isses
Thanks!
