### ISSUE TITLE
product_price_currency null check

### ISSUE THREAD

**Issue by levkar** [adhoc-dev/odoo-addons#166]
one of our clients reported this bug. when you delete the currency in product form it gives error. null check can be made in this line:

https://github.com/ingadhoc/odoo-addons/blob/8.0/product_price_currency/product.py#L38

if product.sale_price_currency_id and product.sale_price_currency_id != company_currency:

**Comment by jjscarafia** [comment]
Thanks! Fixed on https://github.com/ingadhoc/odoo-addons/pull/167
