### ISSUE TITLE
Disappearance. What happened with adhoc_base_setup in branch 8.0 on odoo-addons?

### ISSUE THREAD

**Issue by coolebrax** [adhoc-dev/odoo-addons#182]
I need the "adhoc menú addons" which were in previous versions. What happened with it?

Best regards

Santiago Palacios

**Comment by jjscarafia** [comment]
Esos módulos los mudamos a este repositorio https://github.com/ingadhoc/odoo-setup
Se nos estaba haciendo dificil mantenerlos actualizados en cuanto a descripciones, módulos disponibles y traducciones, va a seguir así, con baja prioridad para nosotros. Si quieren hacer PR super bienvenidos!
