### ISSUE TITLE
Contracts are not set as 'to renew' when the end date is reached

### ISSUE THREAD

**Issue by valentinthirion** [adhoc-dev/odoo-addons#194]
It would probably be interresting to create a CRON that sets the contracts in 'to renew' mode when the 'end date' is reached. Because if not, recurring invoices are still being created.
Thank you

**Comment by jjscarafia** [comment]
It is not done by the default odoo cron that works on sale contracts? If not, good idea, PR wellcome. I'm not sure why our team didn't require it...

**Comment by gonzaloruzafa** [comment]
Valentin/Juan

Contracts are set to "to renew" when end date is reached at the current
state, I use this functionality daily. I don't think further developments
are required

Regards!

**Comment by jjscarafia** [comment]
Thanks @gonzaloruzafa

**Comment by valentinthirion** [comment]
Thanks
