### ISSUE TITLE
account_bank_voucher

### ISSUE THREAD

**Issue by andhit-r** [adhoc-dev/odoo-addons#208]
Hi,

I notice that there is account_bank_voucher module on odoo apps. That module point to this repo, but i could not find it. Would you give me a clue where i could find that module. 

Many thanks.

**Comment by gonzaloruzafa** [comment]
Take a look at this! The module was depreciated, here's a guide:

https://github.com/ingadhoc/odoo-addons/blob/3e31a4b56ff178c081a45bfc0c8d389934e69a1f/CHANGELOG.md

Hope it helps!

**Comment by jjscarafia** [comment]
As Gonzalo sayd, that module was depreceated, use "account_statement_move_import" now, better aproach!

**Comment by andhit-r** [comment]
@gonzaloruzafa @jjscarafia thank you both for the info. Checking account_statement_move_import now.

**Comment by gonzaloruzafa** [comment]
No problem!
