### ISSUE TITLE
Product Pack: Product quantity doens change when packed and soled in the POS

### ISSUE THREAD

**Issue by ferdjaoui** [adhoc-dev/odoo-addons#210]
in the module "product_pack" for a product pack, the sale in the POS doesn't change the available quantity for the pack and for the integrated products, it works only in sales orders.

**Comment by jjscarafia** [comment]
Sorry but pack is not compatibile with pos, PR are wellcome!

**Comment by jjscarafia** [comment]
moved to https://github.com/ingadhoc/product/issues/15

**Comment by mohamedhagag** [comment]
I've made this enhancement in a module

https://github.com/mohamedhagag/dvit-odoo8/tree/8.0/product_pack_pos

should we merge it with the parent module ?
