### ISSUE TITLE
crm_partner_history, not working as expected

### ISSUE THREAD

**Issue by antoniocanovas** [adhoc-dev/odoo-addons#217]
Hi, I have installed this module and tested in odoo v8 with no errors (updated yesterday).
After create several opportunities and mark as winned or losed, nothing appeas in "history".
Phone calls and meetings work fine.
Something wrong?
Thank you.

**Comment by jjscarafia** [comment]
Odoo defines the oportunities field on partner as the one that are opened. As you can see from res_partner.py con crm module
        'opportunity_ids': fields.one2many('crm.lead', 'partner_id',\
            'Leads and Opportunities', domain=[('probability', 'not in', ['0', '100'])]),

I've change it to show all leads making a new field, closed by https://github.com/ingadhoc/odoo-addons/commit/3ab806da668eb6153bba27df334625ed90460960

**Comment by antoniocanovas** [comment]
:+1: 
Gracias y enhorabuena por la rapidez.
