### ISSUE TITLE
inter_company_rules not using taxes for Purchase Order

### ISSUE THREAD

**Issue by aitorbouzas** [adhoc-dev/odoo-addons#220]
Hello,

Thank you for this nice module.
I've noticed that when a Purchase Order is automatically created from an inter-company rule it doesn't contain it's taxes in the lines...

Thanks for your support.

**Comment by jjscarafia** [comment]
Are you sure? Do you have taxes configured on both companies? We have many customers using it with taxes, but I'm not sure if they use SO to PO or PO to SO (I think they use the second one...)

**Comment by aitorbouzas** [comment]
Yes, I have this:
1. Parent company with it's own accounting (including taxes, etc.)
2. Son company with it's own accounting (including taxes, journals, etc.)

I configured one of the companies to create Purchase Orders when selling to it. So I create a Sale Order from the Parent Company to that son, and it happens what I explained... No taxes in the line.

Could it be that the product is using by default the taxes that belong to the father company (defined in the product)? If it is so, maybe the son company can't use that tax in the PO...

**Comment by jjscarafia** [comment]
I think you should have default taxes for both companies, let said, log in
into destiny company (the one that is going to have the PO) and create the
PO manually with those products, are taxes load?

**Comment by aitorbouzas** [comment]
Yes, they load.

**Comment by aitorbouzas** [comment]
No, wait, they don't load. Let me check a second... They were loading because I was with superadmin user...

**Comment by aitorbouzas** [comment]
Ok, just found the problem. I was watching the products always with superadmin user, but when I logged with a restricted user onto the destiny company saw that the product hadn't any tax by default...

**Comment by jjscarafia** [comment]
Common error, working with admin on multicompany env is dangerous! rss
