### ISSUE TITLE
inter_company_rules not creating Sale Order

### ISSUE THREAD

**Issue by aitorbouzas** [adhoc-dev/odoo-addons#223]
Hi,

I'm trying now, to do the reverse thing. From a Purchase Order, create a Sale Order in the related company. It won't create the SO whatever I do. I tried to use admin as the responsible user for the SO. I tried to create use other users with Purchase permission of the company... But nothing seems to happen.

Also, I added some log's onto wkf_confirm_order method in the object purchase_order inherited in this module, but it seems that it is not being executed.

**Comment by aitorbouzas** [comment]
Just saw that I was debugging a file that was not imported from **init**.py...

**Comment by jjscarafia** [comment]
Ah, yea, because this module is a backport of the Odoo one, we only
implement what our customers needs

**Comment by aitorbouzas** [comment]
Ok, I just solved my problem... Was some misconfiguration! Thanks again and sorry for opening another Issue.
