### ISSUE TITLE
[8.0] Move Product pack to OCA?

### ISSUE THREAD

**Issue by rafaelbn** [adhoc-dev/odoo-addons#244]
Hi @ingadhoc @jjscarafia 

We are going to continue this work in OCA

https://github.com/OCA/product-attribute/pull/6

@pedrobaeza told us that you have same work here: https://github.com/ingadhoc/odoo-addons/tree/8.0/product_pack

I think best way is moving https://github.com/ingadhoc/odoo-addons/tree/8.0/product_pack yo OCA

What do you think?

Thanks
Regards,
Rafael

**Comment by jjscarafia** [comment]
We have a pending task to move it to OCA
I'm in my honey moon, on my return I can work on this of if you prefer just
make a PR and add it to OCA.
Thanks!

**Comment by rafaelbn** [comment]
Done, thanks.
