### ISSUE TITLE
 Error installing account_journal_book 

### ISSUE THREAD

**Issue by jmarti15** [adhoc-dev/odoo-addons#250]
Hi, when I install account_journal_book on Odoo 9.0c, I get this error: 
[error2.txt](https://github.com/ingadhoc/odoo-addons/files/66664/error2.txt)

The problem is mine? Am I missing a module or configuration?
Greetings

**Comment by jjscarafia** [comment]
I've remove v9 branch as modules are not yet migrated. Will do it in one or two months

**Comment by jmarti15** [comment]
tx :)
