### ISSUE TITLE
[9.0] product_catalog_aeroo_report & Other Aeroo-related modules

### ISSUE THREAD

**Issue by lukebranch** [adhoc-dev/odoo-addons#251]
@jjscarafia ,

Aeroo reports is now working in Odoo 9.0 thanks to some syntax changes from (@)yenthe666 and a fix in odoo 8.0 that hopefully will be forward ported to 9.0 soon here:

https://github.com/odoo/odoo/pull/10080/files

i'm using this change in 9.0 already and it's working great.

From what I can see your product_catalog_aeroo_report module is working great in version 9.0 (although example reports need to be modified slightly) and i've only needed to change this line in https://github.com/ingadhoc/odoo-addons/blob/8.0/product_catalog_aeroo_report/wizard/product_catalog_wizard.xml:

```
        <menuitem
                id="menu_product_catalog"
                action="action_product_catalog"
                parent="base.menu_product"
                sequence="20"/>
```

to this:

```
        <menuitem
                id="menu_product_catalog"
                action="action_product_catalog"
                parent="base.menu_sale_report"
                sequence="20"/>
```

to allow it to appear in the menu under Sales >> Reports >> Product Catalog.

The only thing I have not yet managed to get working in 9.0 is images in reports, although I will be troubleshooting this today to find a fix.

Do you have any plans to port this module over to 9.0 officially, or would you accept a PR to a 9.0 branch for that module?

**Comment by jjscarafia** [comment]
Hi! Thanks for the issue. 
Yes, please submit a PR making v 9.0 module instalable and with the fixes and I will accept it

**Comment by lukebranch** [comment]
@jjscarafia ,

thanks! I'll close this issue for now and submit a PR with the changes for version 9.0 soon.
