### ISSUE TITLE
[8.0][BUG][inter_company_rules] supplier invoice validate error

### ISSUE THREAD

**Issue by robornetx** [adhoc-dev/odoo-addons#269]
Hi,

Thank you very much to develop such a good app!

I set up A company and B company, after establishing A company SO, company B can automatically generate the PO;SO can shipment, create and validate the customer invoice, the PO can be receiving, create and validate the supplier invoice, but an error occurred while trying to confirm the supplier invoice.

**ValidateError Field(s) `company_id` failed against a constraint: Account and Period must belong to the same company.**

**Comment by jjscarafia** [comment]
When you create the invoice of company "B" are you using admin? are you log
in in company "A" or another company different than b?

**Comment by jjscarafia** [comment]
Please also move this issue to https://github.com/ingadhoc/multi-company as this repo is depreceated as you can see on https://github.com/ingadhoc/odoo-addons/blob/8.0/README.md

**Comment by robornetx** [comment]
Yes, I use the standard multi-company function. the same database, company "A" and company "B" is parallel, invoice was established using the same user "admin"
