### ISSUE TITLE
When product is shared between companies, check is not done

### ISSUE THREAD

**Issue by droelneo** [adhoc-dev/odoo-addons#270]
When company_id is void on duplicate products, the validation check is not done.

**Comment by jjscarafia** [comment]
This repository is depreceated, see the repository readme file and please
upload the issue to the corresponding repositoy.
Please also sepecify the module and steps to reproduce the error.
More info on how to contributte here [https://github.com/ingadhoc/odoo-argentina/wiki](https://github.com/ingadhoc/odoo-argentina/wiki)

**Comment by droelneo** [comment]
Ok I will do it.

This repository is the one referenced in odoo apps...

**Comment by jjscarafia** [comment]
Yes, sorry, we need to correct that but there is no easy way in odoo, you
can not delete a repository with modules that are bing used by other
repositories. I will get in touch with odoo
