### ISSUE TITLE
update repository on app store

### ISSUE THREAD

**Issue by yelizariev** [adhoc-dev/odoo-addons#275]
Could you please contact support team at apps@odoo.com and ask to update repository for the modules (register new repos at app store and  provide list of modules with new repoitory).
Then your modules will be up-to-date on app store, e.g.
https://github.com/ingadhoc/partner

**Comment by jjscarafia** [comment]
Hi @yelizariev . Just do that, thanks.
We were waiting to this right on v9, but better if  odoo help us and v8 is updated.

**Comment by jjscarafia** [comment]
done!
