### ISSUE TITLE
Price Security issue

### ISSUE THREAD

**Issue by Ayhamhafez** [adhoc-dev/odoo-addons#276]
User in restrict prices group can't open res.partner form at all, get the following error:
AttributeError: Element '<field name="property_product_pricelist">' cannot be located in parent view

Error context:
View `res.partner.product.property.form.inherit`
[view_id: 997, xml_id: price_security.view_partner_property_form, model: res.partner, parent_id: 494]

Without restrict prices option, he can open the form and see the property_product_pricelist feild

**Comment by jjscarafia** [comment]
please, don't use this repository, it has been depreceated. Use ingadhoc/product (or any other). This error already fixed I think...
