### ISSUE TITLE
Price Security issue2

### ISSUE THREAD

**Issue by Ayhamhafez** [adhoc-dev/odoo-addons#277]
User with restrict prices option can't create or view product form from sale order line

AttributeError: Element '<field name="list_price">' cannot be located in parent view

Error context:
View `price_security.product.form`
[view_id: 994, xml_id: price_security.product_readonly_normal_form_view, model: product.product, parent_id: 992]

From product menu he can view the product form normally

**Comment by jjscarafia** [comment]
please, don't use this repository, it has been depreceated. Use ingadhoc/product (or any other). This error already fixed I think...

**Comment by Ayhamhafez** [comment]
Thanks, will check
