### ISSUE TITLE
Conflict with document_page: document_page_extension V7.0

### ISSUE THREAD

**Issue by diassynthesis** [adhoc-dev/odoo-addons#3]
Can't install document_page_approval module (from Savoir-faire Linux).... Can't find field 'hide_title' in the following view parts composing the view of object model 'document.page': \* document.page.form

Cause: record id="document_page.view_wiki_form" model="ir.ui.view" at line 9  
view_wiki_form already exist in module document_page.

Possible solutions:
Change document_page.view...... to document_page_extension.view.....
Or inherit from document_page.view_wiki_form
Maybe just adding a sequence to the form ...

Best regards.

**Comment by jjscarafia** [comment]
Thanks for the issue and the proposal, we are not going to fix it as we are no longer working en v7. If you would like, just propose a PR
