### ISSUE TITLE
Feature Request [8.0] product_catalog_aeroo_report - Is it possible to output one category per sheet/worksheet with this module?

### ISSUE THREAD

**Issue by lukebranch** [adhoc-dev/odoo-addons#31]
@jjscarafia ,

I've just started working with this module in 8.0, and it is proving incredibly useful. Thanks for all your work on this project.

I'd like to ask if it is possible to output category per sheet/worksheet with this module. I've searched through the Alistek forums, as well as help.odoo.com and I can't find anything on this topic.

What I am hoping to accomplish is create a separate worksheet per product category and list all products in that category (and subcategories if possible) in that worksheet.

If you have time I would value your input or advice on this question.

**Comment by jjscarafia** [comment]
Hi! that would be great, but I don't know any native way on aeroo to do that. 
sorry...
