### ISSUE TITLE
Lines in Sale Orders don't respect order in which they are entered after installing nan_product_pack

### ISSUE THREAD

**Issue by andr-rm** [adhoc-dev/odoo-addons#33]
After installing this module Lines in Sale Orders don't respect order in which they are entered. For more details, please check this forum thread:

https://www.odoo.com/forum/help-1/question/lines-in-sale-orders-dont-respect-order-in-which-they-are-entered-69320

The behavior I've noticed is the following, if you enter each product line continuously by clicking "Add an item" and add all items one after another without abandoning the "Create: Order Lines" form by clicking "Save & New", once you're done entering them all this way and click "(update)" or "Save" the Sale Order, the items respect the order in which they where entered. BUT, if for example you add an item by clicking "Add an item" then click "Save & Close" on the ""Create: Order Lines", once you start adding items again, any new items you add will appear after the first line entered in the Sale Order one you save or update it, instead of being places after the LAST line in the sequence they have been added. This behaviour is very annoying specially when creating a quotation with many items, it can get all messed up and you have to drag and drop each item to place them in the intended order.

**Comment by jjscarafia** [comment]
Hi, I will be working on this soon! Thans for reporting!

**Comment by andr-rm** [comment]
gracias!

**Comment by jjscarafia** [comment]
This has been solved on this branch https://github.com/adhoc-dev/odoo-addons/tree/8.0.x.imp_pack
we have made several imp to product pack module, please test and give feeback.
Soon we are going to merge it to ingadhoc 8.0 branch

**Comment by andr-rm** [comment]
I'll test it as soon as I migrate to 8.0 (I'm still on 7.0). thanks!
