### ISSUE TITLE
Associate checks to bank statements 

### ISSUE THREAD

**Issue by csrocha** [adhoc-dev/odoo-addons#36]
When you load bank statements and appear an check deposit, the system must associate this statement to the right check, and set it to paid.

**Comment by ckasimis** [comment]
is this in 8.0 branch or in voucher_payline branch?

**Comment by jjscarafia** [comment]
@csrocha  we are working on that an on another improovements on the voucher_payline branch

**Comment by jjscarafia** [comment]
It is ready this functionlaity, not as defined, but now, you can add deposited checks, debit checks and any manuall move line using account_statement_move_import.
This funcionality is on branch 8.0.x and will be merged on 8.0 after some weeks we test it in production on some customers. Update of modules is not trivial, there are some dependencies you should install by hand. We are also working on migration scripts so you don't need to make any hand modifications on journals (perhups we lunch it today)
Feedback, testing and PR are more than wellcome!

NOTE: in this new branch you will also find account_tax_settlement and account_transfer, two usefull modules that also works with the statements, to test this branch in minuts youn can use this [docker image](http://www.odooargentina.com/page/instalar-con-docker-all-in-one)
