### ISSUE TITLE
Account selection error

### ISSUE THREAD

**Issue by valentinthirion** [adhoc-dev/odoo-addons#46]
Hello,
There is a mistake in the account selection for the product.
Here it takes the 'income' account although it should take the 'expense' account because it's a 'purchase' contracts system.

Am I right?
Thanks for the follo

**Comment by jjscarafia** [comment]
Hi! thanks for the issue. Can you be more specific please? Which module are you refering? Wich code?
Thanks, 
Juan

**Comment by valentinthirion** [comment]
I Juan,
Sorry I though the message was directly linked to the module I was checking.

I'm referring to the "account_analytic_purchase_contract" module.
When a recurring invoice is created, it should set the "expense" account in the invoice lines and not the 'income'.

And as I read in the code on file : account_analytic_purchase_contract/account_analytic_analysis.py
On line 73 there is : account_id = res.property_account_income.id

And should'nt it be 'account_id = res.property_account_expense.id   ?

Thanks for the support.

**Comment by jjscarafia** [comment]
Done. Thanks!

**Comment by valentinthirion** [comment]
Great! That was fast!

Can you tell me how to update the module (knowing that I installed it directly from the module list in Odoo) ? Thanks you

**Comment by jjscarafia** [comment]
Not sure... Yo detect updates Odoo apps requires a version number change..

**Comment by valentinthirion** [comment]
It works!

Thanks you
