### ISSUE TITLE
[v8 account_bank_voucher] Permite doble conciliación  

### ISSUE THREAD

**Issue by ccarly** [adhoc-dev/odoo-addons#70]
Escenario 1:
En un extracto bancario dígito manualmente dos lineas por el mismo valor y tercero, al conciliar la primera, la segunda ya no permite usar el mismo registro en la conciliación.

Escenario 2
En un extracto bancario dígito una linea de un tercero ya con pago registrado, luego importo este pago (que queda conciliado inmediatamente), cuando concilio, permite utilizar el mismo registro para la linea que se digitó.

**Comment by jjscarafia** [comment]
Justo tengo que trabajar en esto, lo tengo en cuenta a ver si puedo replicar y resolverlo!

**Comment by ccarly** [comment]
Muchas gracias por la respuesta, estaré al tanto del progreso y cualquier apoyo que necesites, comentame.

**Comment by jjscarafia** [comment]
same issue as #36
